# Generated by Django 4.1.7 on 2023-10-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_repair_resolution_repair_size_repair_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='samsungrepair',
            name='ratings',
            field=models.FloatField(default=2),
        ),
    ]
